add: blog app
alvinisasi/nextjs-blog pull request #2
Opened 2023-12-19 11:15 UTC by alvinisasi

2023-12-29 00:23 UTC, exneval requested changes

2023-12-29 00:23 UTC, exneval commented on apps/blog/pages/about/index.tsx
> +        revalidate: revalidate
`revalidate: revalidate` -> `revalidate`

2023-12-29 00:23 UTC, exneval commented on apps/blog/pages/about/index.tsx
> +            <HydrationBoundary state={dehydratedState}>
should wrap with hydration context in _app file instead

2023-12-29 00:23 UTC, exneval commented on apps/blog/pages/about/index.tsx
> +    return <Typography variant="body1" color={theme.palette.primary.contrastText}>
no prettier formatting applied

2023-12-29 00:23 UTC, exneval commented on apps/blog/pages/posts/[slug]/index.tsx
> +import { usePathname } from 'next/navigation'
get the pathname from next/router hooks instead

2023-12-29 00:23 UTC, exneval commented on apps/blog/pages/posts/[slug]/index.tsx
> +            <HydrationBoundary state={dehydratedPost}>
should wrap with hydration context in _app file

2023-12-29 00:23 UTC, exneval commented on apps/web/app/layout.tsx
use only pages dir to avoid confusing

2023-12-29 00:23 UTC, exneval commented on apps/web/app/globals.css
only use pages dir to avoid confusing

2023-12-29 00:23 UTC, exneval commented on apps/web/app/favicon.ico
only use pages dir to avoid confusing

2023-12-29 00:23 UTC, exneval commented on apps/web/app/page.module.css
only use pages dir to avoid confusing

2023-12-29 00:23 UTC, exneval commented on apps/web/app/page.tsx
only use pages dir to avoid confusing

2024-01-02 02:24 UTC, alvinisasi commented on apps/blog/pages/about/index.tsx
> +            <HydrationBoundary state={dehydratedState}>
fixed on #3

2024-01-02 02:24 UTC, alvinisasi commented on apps/blog/pages/about/index.tsx
> +        revalidate: revalidate
fixed on #3

2024-01-02 02:24 UTC, alvinisasi commented on apps/blog/pages/about/index.tsx
> +    return <Typography variant="body1" color={theme.palette.primary.contrastText}>
fixed on #2

2024-01-02 02:25 UTC, alvinisasi commented on apps/blog/pages/posts/[slug]/index.tsx
> +import { usePathname } from 'next/navigation'
fixed on #3

2024-01-02 02:25 UTC, alvinisasi commented on apps/blog/pages/posts/[slug]/index.tsx
> +            <HydrationBoundary state={dehydratedPost}>
fixed on #3

2024-01-02 03:04 UTC, alvinisasi commented on apps/web/app/layout.tsx
fixed on #5

2024-01-02 03:04 UTC, alvinisasi commented on apps/web/app/globals.css
fixed on #5

2024-01-02 03:04 UTC, alvinisasi commented on apps/web/app/favicon.ico
fixed on #5

2024-01-02 03:05 UTC, alvinisasi commented on apps/web/app/page.module.css
fixed on #5

2024-01-02 03:05 UTC, alvinisasi commented on apps/web/app/page.tsx
fixed on #5

2024-01-03 01:26 UTC, exneval approved these changes
LGTM

2024-01-03 11:39 UTC, merged